# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6NCJRxjMJFJorLIJri408qF3YEDUjBt
"""

# 1. ربط الدرايف
from google.colab import drive
drive.mount('/content/drive')

# 2. تنصيب المكتبات
!pip install -q langchain-community langchain-huggingface langchain-chroma pypdf sentence-transformers google-generativeai

import os
from langchain_community.document_loaders import PyPDFLoader, DirectoryLoader
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

# تغيير المسار لمجلد المشروع
os.chdir('/content/drive/MyDrive/AgriFinTech_Project')

# إعداد الموديل وقاعدة البيانات
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# تحميل وتقسيم الملفات
loader = DirectoryLoader('data/', glob="./*.pdf", loader_cls=PyPDFLoader)
documents = loader.load()
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = text_splitter.split_documents(documents)

# بناء وحفظ قاعدة البيانات
vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="database/chroma_db"
)
print(f"✅ تم معالجة {len(chunks)} قطعة نصية بنجاح!")

import json
import requests

# قاموس المدن الأردنية لربط قائمة الويبسايت
JORDAN_CITIES = {
    "إربد": {"lat": 32.55, "lon": 35.85},
    "الأغوار الشمالية": {"lat": 32.45, "lon": 35.60},
    "الأغوار الوسطى": {"lat": 32.19, "lon": 35.61},
    "المفرق": {"lat": 32.34, "lon": 36.20},
    "عمان": {"lat": 31.95, "lon": 35.91},
    "الكرك": {"lat": 31.18, "lon": 35.70},
}

def get_soil(lat, lon):
    try:
        # محاولة جلب البيانات من الـ API العالمي
        url = f"https://rest.isric.org/soilgrids/v2.0/properties/query?lon={lon}&lat={lat}&property=phh2o&property=clay&depth=0-5cm&value=mean"
        response = requests.get(url, timeout=10).json()
        layers = response.get('properties', {}).get('layers', [])

        # قيم افتراضية للأمان
        soil_results = {
            "حموضة_التربة": 7.5,
            "نسبة_الطين_بالمئة": 30.0,
            "وصف_التربة": "قاعدية طينية (نموذجية للأردن)" # القيمة الافتراضية هنا
        }

        for layer in layers:
            name = layer.get('name')
            try:
                val = layer['depths'][0]['values']['mean'] / 10
                if name == 'phh2o': soil_results["حموضة_التربة"] = val
                if name == 'clay': soil_results["نسبة_الطين_بالمئة"] = val
            except: continue

        # تحديث الوصف بناءً على النتائج الفعلية
        if soil_results["حموضة_التربة"] >= 7:
            soil_results["وصف_التربة"] = "قاعدية طينية (نموذجية للأردن)"
        else:
            soil_results["وصف_التربة"] = "تربة حامضية"

        return soil_results

    except Exception as e:
        # في حال فشل الـ API تماماً، نرسل هذا القاموس الكامل لضمان عدم توقف الكود
        return {
            "حموضة_التربة": 7.5,
            "نسبة_الطين_بالمئة": 30.0,
            "وصف_التربة": "قاعدية طينية (متوسط التربة الأردنية)",
            "ملاحظة": "تم استخدام بيانات افتراضية بسبب خطأ في الاتصال"
        }

def get_all_data(farmer_name, crop_name, city_name, land_area, loan_amount, experience_years):
    loc = JORDAN_CITIES.get(city_name)
    if not loc: return {"error": "المدينة غير مدعومة"}

    # 1. سحب بيانات المحصول (السعر والتكلفة التقريبية)
    with open('data/crops_data.json', 'r', encoding='utf-8') as f:
        crops = json.load(f)
    crop_info = crops.get(crop_name, {})

    # 2. سحب الطقس والتربة (كما فعلنا سابقاً)
    w_url = f"https://api.open-meteo.com/v1/forecast?latitude={loc['lat']}&longitude={loc['lon']}&daily=temperature_2m_max&timezone=Asia/Amman"
    temp = requests.get(w_url).json()["daily"]["temperature_2m_max"][0]
    soil_data = get_soil(loc['lat'], loc['lon'])

    # 3. سحب إرشادات الـ RAG
    results = vector_db.similarity_search(f"إرشادات زراعة {crop_name}", k=3)
    context = "\n".join([res.page_content for res in results if crop_name in res.page_content])

    # تجميع كل البيانات في حزمة واحدة (Data Bundle)
    return {
        "اسم_المزارع": farmer_name,
        "محصول": crop_name,
        "مدينة": city_name,
        "مساحة_الأرض": land_area,
        "مبلغ_القرض": loan_amount,
        "سنوات_الخبرة": experience_years,
        "سعر_السوق_دينار": crop_info.get("متوسط_السعر_دينار"),
        "الحرارة_الحالية": temp,
        "بيانات_التربة": soil_data,
        "توصية_النظام": context[:500]
    }

import google.generativeai as genai

# 1. إعداد مفتاح الـ API (تأكدي من وضع مفتاحك الشخصي)
GOOGLE_API_KEY = "AIzaSyAVxyE49x8sdKRt8NAZo73WKFuV1XA6ZGY".strip()
genai.configure(api_key=GOOGLE_API_KEY)

# 2. تعريف دالة التقرير النهائي (The Expert Logic)
def get_final_ai_report(data_bundle):
    # استخدام موديل Gemini 1.5 Flash لضمان السرعة في الهاكاثون
    model = genai.GenerativeModel('gemini-2.5-flash')

    soil = data_bundle['بيانات_التربة']

    # صياغة البرومبت الاحترافي الذي يربط الجانب الزراعي بالمالي
    prompt = f"""
    أنت الآن 'خبير أغري-تيك' ومستشار مالي زراعي في الأردن.
    حلل بيانات المزارع التالية وقدم توصية نهائية:

    --- معلومات المزارع الشخصية ---
    - اسم المزارع: {data_bundle['اسم_المزارع']}
    - سنوات الخبرة: {data_bundle['سنوات_الخبرة']} سنة
    - المدينة: {data_bundle['مدينة']}

    --- تفاصيل المشروع والقرض ---
    - المحصول: {data_bundle['محصول']}
    - مساحة الأرض: {data_bundle['مساحة_الأرض']} دونم
    - مبلغ القرض المطلوب: {data_bundle['مبلغ_القرض']} دينار أردني

    --- البيانات اللحظية والبيئية ---
    - سعر السوق الحالي: {data_bundle['سعر_السوق_دينار']} دينار
    - درجة الحرارة: {data_bundle['الحرارة_الحالية']}°C
    - التربة: {soil['وصف_التربة']} (حموضة {soil['حموضة_التربة']} ونسبة طين {soil['نسبة_الطين_بالمئة']}%)
    - إرشادات الوزارة (RAG): {data_bundle['توصية_النظام']}

    --- المطلوب منك (باللهجة الأردنية المهنية - العامية البيضاء) ---
    1. وجه تحية شخصية للمزارع باسمه.
    2. حلل مدى منطقية مبلغ القرض ({data_bundle['مبلغ_القرض']}) لمساحة {data_bundle['مساحة_الأرض']} دونم.
    3. قدم نصيحة ري وتسميد بناءً على دمج (الحرارة + نسبة الطين + الحموضة).
    4. تقييم المخاطرة: هل خبرته ({data_bundle['سنوات_الخبرة']} سنة) والظروف الحالية تسمح له بالسداد؟
    5. التوصية النهائية: اطلب القرض أم انتظر؟ (كن صريحاً جداً).
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"حدث خطأ في التواصل مع المستشار الذكي: {str(e)}"

# --- 🚀 تجربة التشغيل (محاكاة لاستلام البيانات من فورم الويبسايت) ---
# هذه القيم هي التي سترسلها لكِ زميلتكِ الممبر من الموقع:
web_input = {
    "farmer_name": "أبو كمال",
    "crop_name": "بندورة",
    "city_name": "الأغوار الوسطى",
    "land_area": 15,        # 15 دونم
    "loan_amount": 3500,     # 3500 دينار
    "experience_years": 10   # 10 سنوات خبرة
}

# 1. تجميع البيانات (Engine)
try:
    raw_bundle = get_all_data(
        web_input["farmer_name"],
        web_input["crop_name"],
        web_input["city_name"],
        web_input["land_area"],
        web_input["loan_amount"],
        web_input["experience_years"]
    )

    # 2. توليد التقرير (AI)
    final_report = get_final_ai_report(raw_bundle)

    # 3. عرض النتيجة
    print("************************************************")
    print(f"✨ نصيحة المستشار الذكي لـ {web_input['farmer_name']}:")
    print("************************************************")
    print(final_report)

except Exception as e:
    print(f"حدث خطأ أثناء معالجة الطلب: {e}")

import ipywidgets as widgets
from IPython.display import display, clear_output

# 1. تعريف واجهة الإدخال
style = {'description_width': 'initial'}
header = widgets.HTML("<h2>🌱 لوحة تحكم المستشار الزراعي الذكي (تجريبي)</h2>")

farmer_name = widgets.Text(description="اسم المزارع:", placeholder="مثلاً: أبو كمال", style=style)
crop_type = widgets.Dropdown(options=['بندورة', 'زيتون', 'بصل'], description="نوع المحصول:", style=style)
city = widgets.Dropdown(options=list(JORDAN_CITIES.keys()), description="الموقع (المنطقة):", style=style)
land_area = widgets.IntText(description="مساحة الأرض (دونم):", value=10, style=style)
loan_amount = widgets.IntText(description="مبلغ القرض المطلوب:", value=3000, style=style)
experience = widgets.IntSlider(description="سنوات الخبرة:", min=0, max=50, value=5, style=style)

btn_analyze = widgets.Button(description="إصدار التقرير الذكي", button_style='success', icon='check')
output = widgets.Output()

# 2. وظيفة الزر عند الضغط
def on_click_analyze(b):
    with output:
        clear_output()
        print("⏳ جاري تحليل البيانات وسحب تقارير الطقس والتربة...")

        try:
            # استدعاء المحرك الذي بنيناه سابقاً
            raw_bundle = get_all_data(
                farmer_name.value,
                crop_type.value,
                city.value,
                land_area.value,
                loan_amount.value,
                experience.value
            )

            # استدعاء المستشار الذكي (Gemini)
            report = get_final_ai_report(raw_bundle)

            # عرض النتائج بشكل مرتب
            display(widgets.HTML(f"<h3>✅ التقرير النهائي لـ {farmer_name.value}:</h3>"))
            print(report)

        except Exception as e:
            print(f"❌ حدث خطأ: {e}")

btn_analyze.on_click(on_click_analyze)

# 3. عرض اللوحة
input_box = widgets.VBox([
    header, farmer_name, crop_type, city, land_area, loan_amount, experience, btn_analyze
])
display(input_box, output)

